services:
  backend:
    image: ivanln26/iswiii-backend
    build:
      context: ./backend
    container_name: iswiii-backend
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000

  vote-frontend:
    image: ivanln26/iswiii-vote-frontend
    build:
      context: ./vote
    container_name: iswiii-vote-frontend
    depends_on:
      - backend
    ports:
      - 3000:3000

  db:
    image: mysql:8.0.31
    container_name: iswiii-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:7.0.5-alpine
    container_name: iswiii-redis
    ports:
      - 6379:6379

volumes:
  db-data:
