name: Integration Tests

on:
  workflow_dispatch:

  workflow_run:
    workflows: [Backend, Frontend]
    types:
      - completed

env:
  FRONTEND_URI: 'https://frontend-g62olrv22a-uc.a.run.app'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      working-directory: ./integration
      run: pip install -r requirements.txt
    - name: Run tests
      working-directory: ./integration
      run: python main.py
